server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ECCM-Server
  datasource:
    url: jdbc:postgresql://${PGSQL_HOST}:${PGSQL_PORT}/${PGSQL_DB}
    username: ${PGSQL_USER}
    password: ${PGSQL_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always