CREATE TABLE IF NOT EXISTS car_log(
    device_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    car_id TEXT NOT NULL,
    trip_id TEXT NOT NULL,
    gps_latitude double PRECISION NULL,
    gps_longitude double PRECISION NULL,
    gps_altitude double PRECISION NULL,
    gps_speed double PRECISION NULL,
    gps_track double PRECISION NULL,
    engine_load double PRECISION NULL,
    coolant_temp double PRECISION NULL,
    short_fuel_trim_1 double PRECISION NULL,
    long_fuel_trim_1 double PRECISION NULL,
    short_fuel_trim2 double PRECISION NULL,
    long_fuel_trim_2 double PRECISION NULL,
    fuel_pressure double PRECISION NULL,
    intake_pressure double PRECISION NULL,
    rpm double PRECISION NULL,
    speed double PRECISION NULL,
    timing_advance double PRECISION NULL,
    intake_temp double PRECISION NULL,
    maf double PRECISION NULL,
    throttle_pos double PRECISION NULL,
    air_status TEXT NULL,
    o2_sensors TEXT NULL,
    o2_b1_s1 double PRECISION NULL,
    o2_b1_s2 double PRECISION NULL,
    o2_b1_s3 double PRECISION NULL,
    o2_b1_s4 double PRECISION NULL,
    o2_b2_s1 double PRECISION NULL,
    o2_b2_s2 double PRECISION NULL,
    o2_b2_s3 double PRECISION NULL,
    o2_b2_s4 double PRECISION NULL,
    obd_compliance TEXT NULL,
    o2_sensors_alt TEXT NULL,
    aux_input_status TEXT NULL,
    run_time double PRECISION NULL,
    distance_without_mil double PRECISION NULL,
    fuel_rail_pressure_vac double PRECISION NULL,
    fuel_rail_pressure_direct double PRECISION NULL,
    o2_s1_wr_voltage double PRECISION NULL,
    o2_s2_wr_voltage double PRECISION NULL,
    o2_s3_wr_voltage double PRECISION NULL,
    o2_s4_wr_voltage double PRECISION NULL,
    o2_s5_wr_voltage double PRECISION NULL,
    o2_s6_wr_voltage double PRECISION NULL,
    o2_s7_wr_voltage double PRECISION NULL,
    o2_s8_wr_voltage double PRECISION NULL,
    commanded_egr double PRECISION NULL,
    egr_error double PRECISION NULL,
    evaporative_purge double PRECISION NULL,
    fuel_level double PRECISION NULL,
    warmups_since_dtc_clear double PRECISION NULL,
    distance_since_dtc_clear double PRECISION NULL,
    evap_vapor_pressure double PRECISION NULL,
    barometric_pressure double PRECISION NULL,
    o2_s1_wr_current double PRECISION NULL,
    o2_s2_wr_current double PRECISION NULL,
    o2_s3_wr_current double PRECISION NULL,
    o2_s4_wr_current double PRECISION NULL,
    o2_s5_wr_current double PRECISION NULL,
    o2_s6_wr_current double PRECISION NULL,
    o2_s7_wr_current double PRECISION NULL,
    o2_s8_wr_current double PRECISION NULL,
    catalyst_temp_b1_s1 double PRECISION NULL,
    catalyst_temp_b2_s1 double PRECISION NULL,
    catalyst_temp_b1_s2 double PRECISION NULL,
    catalyst_temp_b2_s2 double PRECISION NULL,
    control_module_voltage double PRECISION NULL,
    absolute_load double PRECISION NULL,
    commanded_equiv_ratio double PRECISION NULL,
    relative_throttle_pos double PRECISION NULL,
    ambiant_air_temp double PRECISION NULL,
    throttle_pos_b double PRECISION NULL,
    throttle_pos_c double PRECISION NULL,
    throttle_pos_d double PRECISION NULL,
    throttle_pos_e double PRECISION NULL,
    throttle_pos_f double PRECISION NULL,
    throttle_actuator double PRECISION NULL,
    run_time_mil double PRECISION NULL,
    time_since_dtc_cleared double PRECISION NULL,
    max_maf double PRECISION NULL,
    fuel_type TEXT NULL,
    ethanol_percent double PRECISION NULL,
    abs_evap_vapor_pressure double PRECISION NULL,
    alt_evap_vapor_pressure double PRECISION NULL,
    short_o2_trim_b1 double PRECISION NULL,
    long_o2_trim_b1 double PRECISION NULL,
    short_o2_trim_b2 double PRECISION NULL,
    long_o2_trim_b2 double PRECISION NULL,
    fuel_rail_pressure_abs double PRECISION NULL,
    relative_accel_pos double PRECISION NULL,
    hybrid_battery_remaining double PRECISION NULL,
    oil_temp double PRECISION NULL,
    fuel_inject_timing double PRECISION NULL,
    fuel_rate double PRECISION NULL,
    air_flow_rate double PRECISION  NULL
);


SELECT create_hypertable('car_log','device_time')
WHERE NOT EXISTS (SELECT * FROM timescaledb_information.hypertables WHERE hypertable_name = 'car_log');